<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosPdf\Model\ViewPdfRenderer'          => __DIR__ . '/src/LosPdf/Model/ViewPdfRenderer.php',
    'LosPdf\Model\ViewPdfStrategy'          => __DIR__ . '/src/LosPdf/Model/ViewPdfStrategy.php',
    'LosPdf\Module'                         => __DIR__ . '/src/LosPdf/Module.php',
    'LosPdf\View\Model\PdfModel'            => __DIR__ . '/src/LosPdf/View/Model/PdfModel.php',
    'LosPdf\View\Renderer\AbstractRenderer' => __DIR__ . '/src/LosPdf/View/Renderer/AbstractRenderer.php',
    'LosPdf\View\Renderer\MpdfRenderer'     => __DIR__ . '/src/LosPdf/View/Renderer/MpdfRenderer.php',
    'LosPdf\View\Strategy\PdfStrategy'      => __DIR__ . '/src/LosPdf/View/Strategy/PdfStrategy.php',
);
