<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosPdf\Model\ViewPdfRender'          => __DIR__ . '/src/LosPdf/Model/ViewPdfRender.php',
    'LosPdf\Model\ViewPdfStrategy'        => __DIR__ . '/src/LosPdf/Model/ViewPdfStrategy.php',
    'LosPdf\Module'                       => __DIR__ . '/src/LosPdf/Module.php',
    'LosPdf\View\Model\PdfModel'          => __DIR__ . '/src/LosPdf/View/Model/PdfModel.php',
    'LosPdf\View\Render\AbstractRenderer' => __DIR__ . '/src/LosPdf/View/Render/AbstractRenderer.php',
    'LosPdf\View\Render\MpdfRenderer'     => __DIR__ . '/src/LosPdf/View/Render/MpdfRenderer.php',
    'LosPdf\View\Strategy\PdfStrategy'    => __DIR__ . '/src/LosPdf/View/Strategy/PdfStrategy.php',
);
